### ISSUE TITLE
Incorrect format in some Allele Frequencies

### ISSUE THREAD

**Issue by wnewell** [Ensembl/postgap#102]
In columns 4-8
e.g.: 
-:0.8396	-:0.5303	-:0.6448	-:0.67	-:0.4826

**Comment by willmclaren** [comment]
This is likely caused by a temporal bug on the Ensembl REST server; it is now fixed.

Example endpoint: http://grch37.rest.ensembl.org/vep/human/id/rs534193774?content-type=application/json

And the commit for the fix if you're interested: https://github.com/Ensembl/ensembl-vep/commit/03bd5622a127121818deff7a474de97f1dd575dc
